/**
  ******************************************************************************
  * @file    bno055_calib_profile.h
  * @brief   BNO055 calibration profile (offsets + radius, data sheet 3.11.5),
  *          shared through git so every STM32F4 kit loads the same profile.
  *
  *          The profile belongs to the BNO055 module and its mounting,
  *          not to the STM32 kit. Regenerate it after changing module/mounting:
  *            1. Flash firmware, calibrate until CALIB_STAT = 3/3/3/3.
  *            2. Run Tools\bno055_dump_calib.bat (target keeps running).
  *
  *          Generated by Tools/bno055_dump_calib.ps1 on 2026-09-14 16:04
  *            ACC offset X/Y/Z : -18 / -22 / 11 LSB (1 m/s^2 = 100 LSB)
  *            MAG offset X/Y/Z : -184 / 498 / 372 LSB (1 uT = 16 LSB)
  *            GYR offset X/Y/Z : -1 / 3 / -2 LSB (1 dps = 16 LSB)
  *            ACC radius       : 1000 LSB
  *            MAG radius       : 595 LSB
  ******************************************************************************
  */

#ifndef BNO055_CALIB_PROFILE_H
#define BNO055_CALIB_PROFILE_H

#define BNO055_CALIB_PROFILE_VALID  1

/* ACC_OFFSET_X_LSB (0x55) .. MAG_RADIUS_MSB (0x6A) */
#define BNO055_CALIB_PROFILE_DATA \
{ \
  0xEE, 0xFF, 0xEA, 0xFF, 0x0B, 0x00, 0x48, 0xFF, \
  0xF2, 0x01, 0x74, 0x01, 0xFF, 0xFF, 0x03, 0x00, \
  0xFE, 0xFF, 0xE8, 0x03, 0x53, 0x02  \
}

#endif /* BNO055_CALIB_PROFILE_H */
